server:
  port: 8080
spring:
  application:
    name: ExamSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examsystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: bhr050219

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**.xml